Add vcli (vertical cli) output format.

diff --git a/checksec b/checksec
--- a/checksec
+++ b/checksec
@@ -291,16 +291,28 @@ chk_file() {
     printf "\033[m\n"
     exit 1
   fi
-  if ${extended_checks}; then
-    echo_message "RELRO           STACK CANARY      NX            PIE             SELFRANDO             Clang CFI            SafeStack            RPATH      RUNPATH\tSymbols\t\tFORTIFY\tFortified\tFortifiable\tFILE\n" '' '' '{'
+
+  # output the result
+  if [[ $format == vcli ]]; then
+    echo_message "         FILE:  "
+    if [[ "$(find "${CHK_FILE}" \( -perm -004000 -o -perm -002000 \) -type f -print)" ]]; then
+      echo_message "\033[37;41m${CHK_FILE}\033[m\n" ",${CHK_FILE}\n" " filename='${CHK_FILE}'/>\n" " } }"
+    else
+      echo_message "${CHK_FILE}\n" ",${CHK_FILE}\n" " filename='${CHK_FILE}'/>\n" " } }"
+    fi
+    filecheck "${CHK_FILE}"
   else
-    echo_message "RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH\tSymbols\t\tFORTIFY\tFortified\tFortifiable\tFILE\n" '' '' '{'
-  fi
-  filecheck "${CHK_FILE}"
-  if [[ "$(find "${CHK_FILE}" \( -perm -004000 -o -perm -002000 \) -type f -print)" ]]; then
-    echo_message "\033[37;41m${CHK_FILE}\033[m\n" ",${CHK_FILE}\n" " filename='${CHK_FILE}'/>\n" " } }"
-  else
-    echo_message "${CHK_FILE}\n" ",${CHK_FILE}\n" " filename='${CHK_FILE}'/>\n" " } }"
+    if ${extended_checks}; then
+      echo_message "RELRO           STACK CANARY      NX            PIE             SELFRANDO             Clang CFI            SafeStack            RPATH      RUNPATH\tSymbols\t\tFORTIFY\tFortified\tFortifiable\tFILE\n" '' '' '{'
+    else
+      echo_message "RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH\tSymbols\t\tFORTIFY\tFortified\tFortifiable\tFILE\n" '' '' '{'
+    fi
+    filecheck "${CHK_FILE}"
+    if [[ "$(find "${CHK_FILE}" \( -perm -004000 -o -perm -002000 \) -type f -print)" ]]; then
+      echo_message "\033[37;41m${CHK_FILE}\033[m\n" ",${CHK_FILE}\n" " filename='${CHK_FILE}'/>\n" " } }"
+    else
+      echo_message "${CHK_FILE}\n" ",${CHK_FILE}\n" " filename='${CHK_FILE}'/>\n" " } }"
+    fi
   fi
 }
 
@@ -698,6 +710,7 @@ debug_report() {
 # check file(s)
 filecheck() {
   # check for RELRO support
+  if [[ $format == vcli ]]; then echo -n "        RELRO:  "; fi
   if [[ $(${readelf} -l "${1}" 2> /dev/null) =~ "no program headers" ]]; then
     echo_message '\033[32mN/A          \033[m   ' 'N/A,' '<file relro="n/a"' " \"${1}\": { \"relro\":\"n/a\","
   elif ${readelf} -l "${1}" 2> /dev/null | grep -q 'GNU_RELRO'; then
@@ -709,16 +722,20 @@ filecheck() {
   else
     echo_message '\033[31mNo RELRO     \033[m   ' 'No RELRO,' '<file relro="no"' " \"${1}\": { \"relro\":\"no\","
   fi
+  if [[ $format == vcli ]]; then echo; fi
 
   # check for stack canary support
+  if [[ $format == vcli ]]; then echo -n " STACK CANARY:  "; fi
   if ${readelf} -s "${1}" 2> /dev/null | grep " UND " | grep -Eq '__stack_chk_fail|__stack_chk_guard|__intel_security_cookie'; then
     echo_message '\033[32mCanary found   \033[m   ' 'Canary found,' ' canary="yes"' '"canary":"yes",'
   else
     echo_message '\033[31mNo canary found\033[m   ' 'No Canary found,' ' canary="no"' '"canary":"no",'
   fi
+  if [[ $format == vcli ]]; then echo; fi
 
   # check for NX support
   # shellcheck disable=SC2126
+  if [[ $format == vcli ]]; then echo -n "           NX:  "; fi
   if [[ $(${readelf} -l "${1}" 2> /dev/null) =~ "no program headers" ]]; then
     echo_message '\033[32mN/A        \033[m   ' 'N/A,' ' nx="n/a"' '"nx":"n/a",'
   elif ${readelf} -l "${1}" 2> /dev/null | grep -q 'GNU_STACK'; then
@@ -730,8 +747,10 @@ filecheck() {
   else
     echo_message '\033[31mNX disabled\033[m   ' 'NX disabled,' ' nx="no"' '"nx":"no",'
   fi
+  if [[ $format == vcli ]]; then echo; fi
 
   # check for PIE support
+  if [[ $format == vcli ]]; then echo -n "          PIE:  "; fi
   if ${readelf} -h "${1}" 2> /dev/null | grep -q 'Type:[[:space:]]*EXEC'; then
     echo_message '\033[31mNo PIE       \033[m   ' 'No PIE,' ' pie="no"' '"pie":"no",'
   elif ${readelf} -h "${1}" 2> /dev/null | grep -q 'Type:[[:space:]]*DYN'; then
@@ -745,14 +764,17 @@ filecheck() {
   else
     echo_message '\033[33mNot an ELF file\033[m   ' 'Not an ELF file,' ' pie="not_elf"' '"pie":"not_elf",'
   fi
+  if [[ $format == vcli ]]; then echo; fi
 
   if ${extended_checks}; then
     # check for selfrando support
+    if [[ $format == vcli ]]; then echo -n "    SELFRANDO:  "; fi
     if ${readelf} -S "${1}" 2> /dev/null | grep -c 'txtrp' | grep -q '1'; then
       echo_message '\033[32mSelfrando enabled  \033[m   '
     else
       echo_message '\033[31mNo Selfrando       \033[m   '
     fi
+    if [[ $format == vcli ]]; then echo; fi
   fi
 
   if ${extended_checks}; then
@@ -760,23 +782,28 @@ filecheck() {
     #if $readelf -s "$1" 2>/dev/null | grep -Eq '\.cfi'; then
     read -r cfifunc <<< "$($readelf -s "${1}" 2> /dev/null | grep '\.cfi' | awk '{ print $8 }')"
     func=${cfifunc/.cfi/}
+    if [[ $format == vcli ]]; then echo -n "    Clang CFI:  "; fi
     if [ -n "$cfifunc" ] && $readelf -s "$1" 2> /dev/null | grep -q "$func$"; then
       echo_message '\033[32mClang CFI found   \033[m   ' 'with CFI,' ' clangcfi="yes"' '"clangcfi":"yes",'
     else
       echo_message '\033[31mNo Clang CFI found\033[m   ' 'without CFI,' ' clangcfi="no"' '"clangcfi":"no",'
     fi
+    if [[ $format == vcli ]]; then echo; fi
 
     # check if compiled with Clang SafeStack
+    if [[ $format == vcli ]]; then echo -n "    SafeStack:  "; fi
     if $readelf -s "$1" 2> /dev/null | grep -Eq '__safestack_init'; then
       echo_message '\033[32mSafeStack found   \033[m   ' 'with SafeStack,' ' safestack="yes"' '"safestack":"yes",'
     else
       echo_message '\033[31mNo SafeStack found\033[m   ' 'without SafeStack,' ' safestack="no"' '"safestack":"no",'
     fi
+    if [[ $format == vcli ]]; then echo; fi
   fi
 
   # check for rpath / run path
   # search for a line that matches RPATH and extract the colon-separated path list within brackets
   # example input: "0x000000000000000f (RPATH) Library rpath: [/lib/systemd:/lib/apparmor]"
+  if [[ $format == vcli ]]; then echo -n "        RPATH:  "; fi
   if [[ $(${readelf} -d "${1}" 2> /dev/null) =~ "no dynamic section" ]]; then
     echo_message '\033[32mN/A      \033[m  ' 'N/A,' ' rpath="n/a"' '"rpath":"n/a",'
   else
@@ -791,8 +818,10 @@ filecheck() {
       echo_message '\033[32mNo RPATH \033[m  ' 'No RPATH,' ' rpath="no"' '"rpath":"no",'
     fi
   fi
+  if [[ $format == vcli ]]; then echo; fi
 
   # search for a line that matches RUNPATH and extract the colon-separated path list within brackets
+  if [[ $format == vcli ]]; then echo -n "      RUNPATH:  "; fi
   if [[ $(${readelf} -d "${1}" 2> /dev/null) =~ "no dynamic section" ]]; then
     echo_message '\033[32mN/A        \033[m  ' 'N/A,' ' runpath="n/a"' '"runpath":"n/a",'
   else
@@ -807,14 +836,17 @@ filecheck() {
       echo_message '\033[32mNo RUNPATH \033[m  ' 'No RUNPATH,' ' runpath="no"' '"runpath":"no",'
     fi
   fi
+  if [[ $format == vcli ]]; then echo; fi
 
   # check for stripped symbols in the binary
+  if [[ $format == vcli ]]; then echo -n "      Symbols:  "; fi
   IFS=" " read -r -a SYM_cnt <<< "$(${readelf} --symbols "${1}" 2> /dev/null | grep '\.symtab' | cut -d' ' -f5 | cut -d: -f1)"
   if ${readelf} --symbols "${1}" 2> /dev/null | grep -q '\.symtab'; then
     echo_message "\033[31m${SYM_cnt[0]} Symbols\t\033[m  " 'Symbols,' ' symbols="yes"' '"symbols":"yes",'
   else
     echo_message '\033[32mNo Symbols\t\033[m  ' 'No Symbols,' ' symbols="no"' '"symbols":"no",'
   fi
+  if [[ $format == vcli ]]; then echo; fi
 
   search_libc
 
@@ -825,21 +857,29 @@ filecheck() {
   FS_cnt_unchecked=$(grep -cFxf <(sort <<< "${FS_func_libc}") <(sort <<< "${FS_func}"))
   FS_cnt_total=$((FS_cnt_unchecked + FS_cnt_checked))
 
+  if [[ $format == vcli ]]; then echo -n "      FORTIFY:  "; fi
   if grep -q '_chk$' <<< "$FS_func"; then
     echo_message '\033[32mYes\033[m' 'Yes,' ' fortify_source="yes" ' '"fortify_source":"yes",'
   else
     echo_message "\033[31mNo\033[m" "No," ' fortify_source="no" ' '"fortify_source":"no",'
   fi
+  if [[ $format == vcli ]]; then echo; fi
+
+  if [[ $format == vcli ]]; then echo -n "    Fortified:"; fi
   echo_message "\t${FS_cnt_checked}\t" "${FS_cnt_checked}", "fortified=\"${FS_cnt_checked}\" " "\"fortified\":\"${FS_cnt_checked}\","
+  if [[ $format == vcli ]]; then echo; fi
+
+  if [[ $format == vcli ]]; then echo -n "  Fortifiable:"; fi
   echo_message "\t${FS_cnt_total}\t\t" "${FS_cnt_total}" "fortify-able=\"${FS_cnt_total}\"" "\"fortify-able\":\"${FS_cnt_total}\""
+  if [[ $format == vcli ]]; then echo; fi
 }
 
 # format
 format() {
-  list="cli csv xml json"
+  list="cli csv xml json vcli"
   if [[ -n "${output_format}" ]]; then
     if [[ ! ${list} =~ ${output_format} ]]; then
-      printf "\033[31mError: Please provide a valid format {cli, csv, xml, json}.\033[m\n\n"
+      printf "\033[31mError: Please provide a valid format {cli, csv, xml, json, vcli}.\033[m\n\n"
       exit 1
     fi
   fi
@@ -949,7 +989,7 @@ isNumeric() {
 
 # help
 help() {
-  echo "Usage: checksec [--format={cli,csv,xml,json}] [OPTION]"
+  echo "Usage: checksec [--format={cli,csv,xml,json,vcli}] [OPTION]"
   echo
   echo
   echo "Options:"
@@ -974,8 +1014,8 @@ help() {
   echo " ## Modifiers"
   echo "  --debug"
   echo "  --verbose"
-  echo "  --format={cli,csv,xml,json}"
-  echo "  --output={cli,csv,xml,json}"
+  echo "  --format={cli,csv,xml,json,vcli}"
+  echo "  --output={cli,csv,xml,json,vcli}"
   echo "  --extended"
   echo
   echo "For more information, see:"
@@ -1819,6 +1859,13 @@ for variable in CHK_DIR CHK_FILE CHK_FORTIFY_FILE CHK_FORTIFY_PROC CHK_PROC CHK_
     fi
   fi
 done
+
+if [[ $format == vcli ]]; then
+  if [[ -z $CHK_FILE ]]; then
+    printf "\033[31mError: vcli format only works for individual files.\033[m\n\n"
+    exit 1
+  fi
+fi
 
 # call the function
 ${CHK_FUNCTION}
